### ISSUE TITLE
`event` should be `e` in three_mmi.js

### ISSUE THREAD

**Issue by qianzhong516** [danielblagy/three_mmi#1]
Hi, thanks for sharing your great work. I found one mistake in `three_mmi.js`: in the below 2 lines, `event` should be `e` instead. That breaks the script and it didn't work for me before I made the change.
https://github.com/danielblagy/three_mmi/blob/e3215d5211068118ba0db04c23fa6badaaf02efb/three_mmi.js#L188
https://github.com/danielblagy/three_mmi/blob/e3215d5211068118ba0db04c23fa6badaaf02efb/three_mmi.js#L189

**Comment by danielblagy** [comment]
Hi Janice, thank you so much for bringing it to my attention.
You're absolutely right, the reference to 'event' here is deprecated. It still works for the two browsers I've tested it in, but perhaps in the newer versions it's not allowed.

Anyhow, this is a mistake , and the only reason it used to work was because there used to be a global 'event' object so that you wouldn't have to declare an event argument in an event handler function, which is now deprecated.

It's corrected in [this commit](https://github.com/danielblagy/three_mmi/commit/122e968180aad6c1f15d6ccd7b2d9a5ea1fef170).

Thank you once again!

**Comment by qianzhong516** [comment]
> Hi Janice, thank you so much for bringing it to my attention.
> You're absolutely right, the reference to 'event' here is deprecated. It still works for the two browsers I've tested it in, but perhaps in the newer versions it's not allowed.
> 
> Anyhow, this is a mistake , and the only reason it used to work was because there used to be a global 'event' object so that you wouldn't have to declare an event argument in an event handler function, which is now deprecated.
> 
> It's corrected in [this commit](https://github.com/danielblagy/three_mmi/commit/122e968180aad6c1f15d6ccd7b2d9a5ea1fef170).
> 
> Thank you once again!

No worries, thanks for letting me know the historical reason :)
